create extension if not exists pgcrypto;

drop function if exists approve_loan(integer, integer, integer);
drop function if exists return_loan(integer, integer);
drop function if exists approve_extension(integer, integer);
drop function if exists set_updated_at();

drop table if exists riwayat cascade;
drop table if exists perpanjangan cascade;
drop table if exists pengembalian cascade;
drop table if exists peminjaman cascade;
drop table if exists notifikasi cascade;
drop table if exists buku cascade;
drop table if exists admin cascade;
drop table if exists mahasiswa cascade;

create table admin (
  id_admin integer generated by default as identity primary key,
  nama_admin varchar(100) not null,
  email_admin varchar(100) not null unique,
  password_hash text not null,
  jabatan varchar(80) default 'Petugas Perpustakaan',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table mahasiswa (
  npm varchar(20) primary key,
  nama varchar(100) not null,
  email varchar(100) not null unique,
  password_hash text not null,
  nomor_induk varchar(40),
  jurusan varchar(100),
  no_telepon varchar(30),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table buku (
  id_buku integer generated by default as identity primary key,
  judul varchar(160) not null,
  penulis varchar(120) not null,
  penerbit varchar(120),
  tahun_terbit integer,
  isbn varchar(30),
  kategori varchar(80),
  lokasi_rak varchar(40),
  stok integer not null default 0 check (stok >= 0),
  cover_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table peminjaman (
  id_pinjam integer generated by default as identity primary key,
  npm varchar(20) not null references mahasiswa(npm) on delete restrict on update cascade,
  id_buku integer not null references buku(id_buku) on delete restrict on update cascade,
  id_admin integer references admin(id_admin) on delete set null on update cascade,
  tanggal_pinjam date,
  tanggal_jatuh_tempo date,
  tanggal_kembali_real date,
  status_peminjaman varchar(20) not null default 'menunggu'
    check (status_peminjaman in ('menunggu', 'disetujui', 'ditolak', 'dipinjam', 'dikembalikan')),
  alasan_ditolak text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table pengembalian (
  id_kembali integer generated by default as identity primary key,
  id_admin integer references admin(id_admin) on delete set null on update cascade,
  tanggal_kembali date not null default current_date,
  id_pinjam integer not null unique references peminjaman(id_pinjam) on delete restrict on update cascade,
  created_at timestamptz default now()
);

create table perpanjangan (
  id_perpanjangan integer generated by default as identity primary key,
  id_admin integer references admin(id_admin) on delete set null on update cascade,
  id_pinjam integer not null references peminjaman(id_pinjam) on delete restrict on update cascade,
  tanggal_perpanjangan date,
  durasi_perpanjangan integer not null default 7 check (durasi_perpanjangan between 1 and 30),
  status_perpanjangan varchar(20) not null default 'menunggu'
    check (status_perpanjangan in ('menunggu', 'disetujui', 'ditolak')),
  alasan_ditolak text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table riwayat (
  id_riwayat integer generated by default as identity primary key,
  id_pinjam integer not null unique references peminjaman(id_pinjam) on delete restrict on update cascade,
  created_at timestamptz default now()
);

create table notifikasi (
  id_notif integer generated by default as identity primary key,
  npm varchar(20) references mahasiswa(npm) on delete cascade on update cascade,
  id_admin integer references admin(id_admin) on delete cascade on update cascade,
  target_role varchar(20) not null check (target_role in ('mahasiswa', 'admin')),
  email_tujuan varchar(100) not null,
  pesan text not null,
  jenis varchar(40) not null default 'status',
  tanggal_notif timestamptz not null default now(),
  sudah_dibaca boolean not null default false,
  email_status varchar(30) not null default 'pending',
  sent_at timestamptz,
  created_at timestamptz default now()
);

create index idx_buku_judul on buku using gin (to_tsvector('simple', judul || ' ' || penulis || ' ' || coalesce(kategori, '')));
create index idx_peminjaman_npm on peminjaman(npm);
create index idx_peminjaman_status on peminjaman(status_peminjaman);
create index idx_peminjaman_jatuh_tempo on peminjaman(tanggal_jatuh_tempo);
create index idx_perpanjangan_status on perpanjangan(status_perpanjangan);
create index idx_notifikasi_mahasiswa on notifikasi(npm, sudah_dibaca);
create index idx_notifikasi_admin on notifikasi(id_admin, sudah_dibaca);

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger admin_updated_at before update on admin
for each row execute function set_updated_at();

create trigger mahasiswa_updated_at before update on mahasiswa
for each row execute function set_updated_at();

create trigger buku_updated_at before update on buku
for each row execute function set_updated_at();

create trigger peminjaman_updated_at before update on peminjaman
for each row execute function set_updated_at();

create trigger perpanjangan_updated_at before update on perpanjangan
for each row execute function set_updated_at();

create or replace function approve_loan(
  p_id_pinjam integer,
  p_id_admin integer,
  p_durasi_hari integer default 7
)
returns peminjaman
language plpgsql
security definer
as $$
declare
  v_loan peminjaman;
  v_stock integer;
begin
  select * into v_loan
  from peminjaman
  where id_pinjam = p_id_pinjam
  for update;

  if not found then
    raise exception 'Peminjaman tidak ditemukan';
  end if;

  if v_loan.status_peminjaman <> 'menunggu' then
    raise exception 'Peminjaman sudah diproses';
  end if;

  select stok into v_stock
  from buku
  where id_buku = v_loan.id_buku
  for update;

  if coalesce(v_stock, 0) <= 0 then
    raise exception 'Stok buku habis';
  end if;

  update buku
  set stok = stok - 1
  where id_buku = v_loan.id_buku;

  update peminjaman
  set
    id_admin = p_id_admin,
    status_peminjaman = 'disetujui',
    tanggal_pinjam = current_date,
    tanggal_jatuh_tempo = current_date + greatest(p_durasi_hari, 1),
    alasan_ditolak = null
  where id_pinjam = p_id_pinjam
  returning * into v_loan;

  return v_loan;
end;
$$;

create or replace function return_loan(
  p_id_pinjam integer,
  p_id_admin integer
)
returns peminjaman
language plpgsql
security definer
as $$
declare
  v_loan peminjaman;
begin
  select * into v_loan
  from peminjaman
  where id_pinjam = p_id_pinjam
  for update;

  if not found then
    raise exception 'Peminjaman tidak ditemukan';
  end if;

  if v_loan.status_peminjaman not in ('disetujui', 'dipinjam') then
    raise exception 'Peminjaman tidak aktif';
  end if;

  update peminjaman
  set
    id_admin = p_id_admin,
    status_peminjaman = 'dikembalikan',
    tanggal_kembali_real = current_date
  where id_pinjam = p_id_pinjam
  returning * into v_loan;

  update buku
  set stok = stok + 1
  where id_buku = v_loan.id_buku;

  insert into pengembalian (id_admin, tanggal_kembali, id_pinjam)
  values (p_id_admin, current_date, p_id_pinjam)
  on conflict (id_pinjam)
  do update set id_admin = excluded.id_admin, tanggal_kembali = excluded.tanggal_kembali;

  insert into riwayat (id_pinjam)
  values (p_id_pinjam)
  on conflict (id_pinjam) do nothing;

  return v_loan;
end;
$$;

create or replace function approve_extension(
  p_id_perpanjangan integer,
  p_id_admin integer
)
returns perpanjangan
language plpgsql
security definer
as $$
declare
  v_extension perpanjangan;
  v_loan peminjaman;
begin
  select * into v_extension
  from perpanjangan
  where id_perpanjangan = p_id_perpanjangan
  for update;

  if not found then
    raise exception 'Perpanjangan tidak ditemukan';
  end if;

  if v_extension.status_perpanjangan <> 'menunggu' then
    raise exception 'Perpanjangan sudah diproses';
  end if;

  select * into v_loan
  from peminjaman
  where id_pinjam = v_extension.id_pinjam
  for update;

  if v_loan.status_peminjaman not in ('disetujui', 'dipinjam') then
    raise exception 'Peminjaman tidak aktif';
  end if;

  update peminjaman
  set tanggal_jatuh_tempo = coalesce(tanggal_jatuh_tempo, current_date) + v_extension.durasi_perpanjangan
  where id_pinjam = v_extension.id_pinjam;

  update perpanjangan
  set
    id_admin = p_id_admin,
    status_perpanjangan = 'disetujui',
    tanggal_perpanjangan = current_date,
    alasan_ditolak = null
  where id_perpanjangan = p_id_perpanjangan
  returning * into v_extension;

  return v_extension;
end;
$$;

alter table admin enable row level security;
alter table mahasiswa enable row level security;
alter table buku enable row level security;
alter table peminjaman enable row level security;
alter table pengembalian enable row level security;
alter table perpanjangan enable row level security;
alter table riwayat enable row level security;
alter table notifikasi enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'book-covers',
  'book-covers',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;
